WebApplication2/Controllers/FirstController.cs
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Services;
using System.Web.Services;
using System.Threading;
using System.Xml;
using WebApplication2.Models;
using System.IO;
using System.Net;
using System.Web.Script.Serialization;

namespace WebApplication2.Controllers
{
    public class FirstController : Controller
    {
        XmlHandler xmlHandler;

        public FirstController()
        {
            this.xmlHandler = new XmlHandler();
        }

        //public static int counter = 0;
        public object Views { get; private set; }

        // GET: First
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult GetCoor()
        {
            PlaneInfo planeInfo = InfoModel.Instance.LoadData();
            Coordinates coor = planeInfo.Coor;
            return Json(coor, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult GetPlaneInfo()
        {
            PlaneInfo planeInfo = InfoModel.Instance.LoadData();
            return Json(planeInfo, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult DisplayPointOrData(string ip, int port)
        {
            IPAddress IP;
            if (IPAddress.TryParse(ip, out IP))
            {
                return RedirectToAction("DisplayPoint", new { ip, port });
            }
            else
            {
                string fileName = ip;
                int time = port;
                InfoModel.Instance.fileName = fileName;
                return RedirectToAction("LoadDataFromFile", new { fileName, time });
            }
        }

        [HttpGet]
        public ViewResult DisplayPoint(string ip, int port)
        {
            InfoModel.Instance.ConnectClient(ip, port);
            PlaneInfo planeInfo = InfoModel.Instance.LoadData();
            Coordinates coor = InfoModel.Instance.LoadData().Coor;
            Session["Lon"] = coor.Lon;
            Session["Lat"] = coor.Lat;
            return View();
        }

        [HttpGet]
        public ViewResult LoadDataFromFile(string fileName, int time)
        {
            Session["time"] = time;
            Session["listOfCoor"] = fileName;
            return View();
        }

        [HttpGet]
        public ActionResult GetCoorFromFile()
        {
            XmlHandler xmlHandler = new XmlHandler();
            List<Coordinates> coorArray = xmlHandler.ReadData(InfoModel.Instance.fileName);
            return Json(coorArray, JsonRequestBehavior.AllowGet);

        }

        [HttpGet]
        public ActionResult DisplayPlaneMovement(string ip, int port, int time)
        {
            InfoModel.Instance.ConnectClient(ip, port);
            Coordinates coor = InfoModel.Instance.LoadData().Coor;
            Session["Lon"] = coor.Lon;
            Session["Lat"] = coor.Lat;
            Session["time"] = time;

            return View();
        }

        [WebMethod]
        public object SaveData(string fileName, string planeInfo)
        {
            this.xmlHandler.SavePlaneInfoToXml(fileName, planeInfo);

            return Json(HttpStatusCode.OK);
        }

        public ActionResult SavePlaneInfo(string ip, int port, int time, int duration, string file)
        {
            XmlHandler xmlHandler = new XmlHandler();
            InfoModel.Instance.ConnectClient(ip, port);
            Coordinates coor = InfoModel.Instance.LoadData().Coor;
            Session["Lon"] = coor.Lon;
            Session["Lat"] = coor.Lat;
            Session["time"] = time;
            Session["duration"] = duration;
            Session["file"] = file;

            return View();
        }
    }
}

WebApplication2/Views/First/DisplayPoint.cshtml
@{
    ViewBag.Title = "DisplayPoint";
    var Lon = Session["Lon"];
    var Lat = Session["Lat"];
}

<body style="margin: 0">
    <canvas id="canvas"></canvas>
</body>
<script>
    const mapImage = new Image();
    const planeImage = new Image();
    const canvas = document.getElementById("canvas");
    const ctx = canvas.getContext('2d');

    mapImage.src = "/Content/old_map.jpg";
    planeImage.src = "/Content/plane.png";

    canvas.width = window.innerWidth;
    canvas.height = window.innerHeight;

    // adjust the longitude values between -180 to 180
    function adjustLon() {
        if (@Lon < 0) {
            return (canvas.width / 2) * (1 - Math.abs(@Lon) / 180);
        } else {
            return (canvas.width / 2) * (1 + Math.abs(@Lon) / 180);
        }
    }
    // adjust the latitude values between -90 to 90
    function adjustLat() {
        if (@Lat < 0) {
            return (canvas.height / 2) * (1 + Math.abs(@Lat) / 90);
        } else {
            return (canvas.height / 2) * (1 - Math.abs(@Lat) / 90);
        }
    }

    const Lon = adjustLon();
    const Lat = adjustLat();

    mapImage.onload = function () {
        scaleToFill(this);
        loadPlane();
    }

    const loadPlane = () => {
        ctx.drawImage(planeImage, Lon, Lat);
    }

    function scaleToFill(img) {
        var scale = Math.max(canvas.width / img.width, canvas.height / img.height);
        var x = (canvas.width / 2) - (img.width / 2) * scale;
        var y = (canvas.height / 2) - (img.height / 2) * scale;
        ctx.drawImage(img, x, y, img.width * scale, img.height * scale);
    }
    
</script>

WebApplication2/Views/First/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Welcome To Nir & Ariel Amazing Web !!!!!!!!!!!</h2>

WebApplication2/Views/First/LoadDataFromFile.cshtml
@{
    ViewBag.Title = "LoadDataFromFile";
    //var coorArray = Session["listOfCoor"];
}

<body style="margin: 0">
    <canvas id="canvas"></canvas>
</body>
<script src="~/scripts/jquery-3.0.0.min.js"></script>
<script>
    var IntervalTime = (@Session["time"] * 1000);
    const mapImage = new Image();
    const planeImage = new Image();
    const canvas = document.getElementById("canvas");
    const ctx = canvas.getContext('2d');

    mapImage.src = "/Content/old_map.jpg";
    planeImage.src = "/Content/plane.png";

    canvas.width = window.innerWidth;
    canvas.height = window.innerHeight;

    // adjust the longitude values between -180 to 180
    function adjustLon(Lon) {
        if (Lon < 0) {
            return (canvas.width / 2) * (1 - Math.abs(Lon) / 180);
        } else {
            return (canvas.width / 2) * (1 + Math.abs(Lon) / 180);
        }
    }
    // adjust the latitude values between -90 to 90
    function adjustLat(Lat) {
        if (Lat < 0) {
            return (canvas.height / 2) * (1 + Math.abs(Lat) / 90);
        } else {
            return (canvas.height / 2) * (1 - Math.abs(Lat) / 90);
        }
    }

    mapImage.onload = function () {
        scaleToFill(mapImage);
    }

    const loadPlane = (Lon,Lat) => {
        ctx.drawImage(planeImage, Lon, Lat);
    }

    function scaleToFill(img) {
        var scale = Math.max(canvas.width / img.width, canvas.height / img.height);
        var x = (canvas.width / 2) - (img.width / 2) * scale;
        var y = (canvas.height / 2) - (img.height / 2) * scale;
        ctx.drawImage(img, x, y, img.width * scale, img.height * scale);
    }
    
    ctx.beginPath();
    @*ctx.moveTo(adjustLon(@Session["Lon"]), adjustLat(@Session["Lat"]));*@
    ctx.strokeStyle = 'red';
    ctx.lineWidth = 3;

    

    const realtimeDraw = function () {
        $.get("/First/GetCoorFromFile", function (data) {

                    var counter = 0;    
                    //ctx.moveTo(adjustLon(data[counter].Lon), adjustLat(data[counter].Lat));
                    //counter++;
                    var realtimeInterval = setInterval(function () {

                        if (counter == data.length) {

                            clearInterval(realtimeInterval);
                            alert("done");
                            return;
                        }

                        if (data[counter].Lon != -1000 && data[counter].Lat != -1000) {
                            const Lon = adjustLon(data[counter].Lon);
                            const Lat = adjustLat(data[counter].Lat);
                            scaleToFill(mapImage);
                            ctx.lineTo(Lon, Lat);
                            loadPlane(Lon, Lat);
                            
                            ctx.stroke();
                            console.log('i', counter);
                            console.log('window.width: ', window.innerWidth);
                            console.log('window.height: ', window.innerHeight);
                            console.log('Lon adjust: ', Lon);
                            console.log('Lat adjust: ', Lat);

                            counter++;
                        }


                    }, IntervalTime);
                    


        });

      
    };

    //var intervalId = setInterval(myTimer, IntervalTime);
    realtimeDraw();
    
</script>

WebApplication2/Views/First/SavePlaneInfo.cshtml
@{
    ViewBag.Title = "SavePlaneInfo";
}
<body style="margin: 0">
    <canvas id="canvas"></canvas>
</body>
<script src="~/scripts/jquery-3.0.0.min.js"></script>
<script src="~/scripts/jquery-3.0.0.js"></script>

<script>
    var IntervalTime = @Session["time"] * 1000;
    var finishTime = @Session["duration"] * 1000;
    //const fileName = "atk2k";
    const fileName = "@Session["file"]";

    const mapImage = new Image();
    const planeImage = new Image();
    const canvas = document.getElementById("canvas");
    const ctx = canvas.getContext('2d');

    mapImage.src = "/Content/old_map.jpg";
    planeImage.src = "/Content/plane.png";

    canvas.width = window.innerWidth;
    canvas.height = window.innerHeight;

    // adjust the longitude values between -180 to 180
    function adjustLon(Lon) {
        if (Lon < 0) {
            return (canvas.width / 2) * (1 - Math.abs(Lon) / 180);
        } else {
            return (canvas.width / 2) * (1 + Math.abs(Lon) / 180);
        }
    }
    // adjust the latitude values between -90 to 90
    function adjustLat(Lat) {
        if (Lat < 0) {
            return (canvas.height / 2) * (1 + Math.abs(Lat) / 90);
        } else {
            return (canvas.height / 2) * (1 - Math.abs(Lat) / 90);
        }
    }

    const loadPlane = (Lon,Lat) => {
        ctx.drawImage(planeImage, Lon, Lat);
    }

    function scaleToFill(img) {
        var scale = Math.max(canvas.width / img.width, canvas.height / img.height);
        var x = (canvas.width / 2) - (img.width / 2) * scale;
        var y = (canvas.height / 2) - (img.height / 2) * scale;
        ctx.drawImage(img, x, y, img.width * scale, img.height * scale);
    }

    ctx.beginPath();
    ctx.moveTo(adjustLon(@Session["Lon"]), adjustLat(@Session["Lat"]));
    ctx.strokeStyle = 'red';
    ctx.lineWidth = 3;

    var dataArr = [];
    var index = 0;
            
    const myTimer = function () {
        
        $.get("/First/GetPlaneInfo", function (data) {
            if (data.Lon != -1000 && data.Lat != -1000) {
                dataArr.push(new Object());  
                dataArr[index]["Lon"] = data.Coor.Lon;
                dataArr[index]["Lat"] = data.Coor.Lat;
                dataArr[index]["Throttle"] = data.Throttle;  
                dataArr[index]["Rudder"] = data.Rudder;  

                const Lon = adjustLon(data.Coor.Lon);
                const Lat = adjustLat(data.Coor.Lat);
                scaleToFill(mapImage);
                loadPlane(Lon, Lat);
                ctx.lineTo(Lon, Lat);
                ctx.stroke();
                index++;
            }
        });
    };

    const sendToServer = function () {
        //clearInterval(intervalId);

        var dataToSend = { "fileName": fileName, "planeInfo": JSON.stringify(dataArr) }

        $.ajax({
            type: "POST",
            traditional: true,
            url: "/First/SaveData",
            content: "application/json;",
            dataType: "json",
            data: dataToSend,
            success: function () {
                console.info("saved successfuly");
            }
        });
    };  

    var intervalId = setInterval(myTimer, IntervalTime);
    myTimer();
    setTimeout(sendToServer, finishTime);
    
</script>

WebApplication2/Views/First/display.cshtml
@{
    ViewBag.Title = "display";
}

<h2>display</h2>
<div>
    <h2>Employee json Get</h2>
    <table>
        <tr>
            <td>Id:  </td>
            <td><p type="text" id="prodId" size="5"></p></td>
        </tr>
        <tr>
            <td>Name:  </td>
            <td><p type="text" id="prodName" size="5"></p></td>
        </tr>
        <tr>
            <td>Salary:  </td>
            <td><p type="text" id="prodSalary" size="5"></p></td>
        </tr>
    </table>

    <div>
        <h2>Search  by  Name</h2>
        <p> Name: </p>
        <input type="text" id="NameID" size="5" />
        <input type="button" id="btnSearch" value="Search" />
        <ul id="lstProducts"></ul>
    </div>

</div>

<script>
    var IntervalTime = @Session["time"] * 1000
    myTimer = (function () {
        $.post( "@Url.Action("GetEmployee")").done(function (xml) {
                var xmlDoc = $.parseXML( xml ),
                $xml = $( xmlDoc ),
                FirstName = $xml.find( "FirstName" ).text();
                LastName = $xml.find( "LastName" ).text();
                Salary = $xml.find("Salary").text();

                $("#prodId").text(FirstName);
                $("#prodName").text(LastName);
                $("#prodSalary").text(Salary);
                
        });
    });
    
    setInterval(myTimer, IntervalTime);
    myTimer();

    $("#btnSearch").click(function () {
        var input = {
            name: $("#NameID").val(),
        };
        $.post("@Url.Action("Search", "First")", input).done(function (data) {
            var xmlDoc = $.parseXML(data),
                $xml = $(xmlDoc),
                FirstName = $xml.find("FirstName").text();
            LastName = $xml.find("LastName").text();
            Salary = $xml.find("Salary").text();

            $("#lstProducts").append("<li>" + FirstName + " " + LastName + " : $" + Salary + "</li>");
        });
    });

</script>

WebApplication2/Views/First/displayPlaneMovement.cshtml
@{
    ViewBag.Title = "DisplayPlaneMovement";
}
<body style="margin: 0">
    <canvas id="canvas"></canvas>
</body>
<script src="~/scripts/jquery-3.0.0.min.js"></script>
<script>
    var IntervalTime = @Session["time"] * 1000;
    const mapImage = new Image();
    const planeImage = new Image();
    const canvas = document.getElementById("canvas");
    const ctx = canvas.getContext('2d');

    mapImage.src = "/Content/old_map.jpg";
    planeImage.src = "/Content/plane.png";

    canvas.width = window.innerWidth;
    canvas.height = window.innerHeight;

    // adjust the longitude values between -180 to 180
    function adjustLon(Lon) {
        if (Lon < 0) {
            return (canvas.width / 2) * (1 - Math.abs(Lon) / 180);
        } else {
            return (canvas.width / 2) * (1 + Math.abs(Lon) / 180);
        }
    }
    // adjust the latitude values between -90 to 90
    function adjustLat(Lat) {
        if (Lat < 0) {
            return (canvas.height / 2) * (1 + Math.abs(Lat) / 90);
        } else {
            return (canvas.height / 2) * (1 - Math.abs(Lat) / 90);
        }
    }

    //mapImage.onload = function () {
    //    scaleToFill(mapImage);
    //}

    const loadPlane = (Lon,Lat) => {
        ctx.drawImage(planeImage, Lon, Lat);
    }

    function scaleToFill(img) {
        var scale = Math.max(canvas.width / img.width, canvas.height / img.height);
        var x = (canvas.width / 2) - (img.width / 2) * scale;
        var y = (canvas.height / 2) - (img.height / 2) * scale;
        ctx.drawImage(img, x, y, img.width * scale, img.height * scale);
    }

    ctx.beginPath();
    ctx.moveTo(adjustLon(@Session["Lon"]), adjustLat(@Session["Lat"]));
    ctx.strokeStyle = 'red';
    ctx.lineWidth = 3;

    const myTimer = function () {
        $.get("/First/GetCoor", function (data) {
            if (data.Lon != -1000 && data.Lat != -1000) {
                const Lon = adjustLon(data.Lon);
                const Lat = adjustLat(data.Lat);
                scaleToFill(mapImage);
                loadPlane(Lon, Lat);
                ctx.lineTo(Lon, Lat);
                ctx.stroke();
            }
        });
    };
    setInterval(myTimer, IntervalTime);
    myTimer();
</script>